/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formGudang;

import formPemasok.ViewMasterPemasok;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class FormIsianGudang extends javax.swing.JFrame {

    /**
     * Creates new form FormIsianGudang
     */
    Map<String, Integer> kategoriMap = new HashMap<>();
    private String taskFormIsianGudang = "CREATE";
    private int idUpdateFormIsianGudang = 0;
    private ViewMasterGudang parentIsianGudang;
    
    public FormIsianGudang() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/_asset/78.png");
        setIconImage(icon.getImage());
        refreshFormIsianGudang();
        gudangNamafield.setText("");
        gudangAlamatfield.setText("");
        gudangStatusField.setSelectedItem("Aktif");
    }
    
    protected void refreshFormIsianGudang(){
        this.taskFormIsianGudang = "CREATE";
        this.idUpdateFormIsianGudang = 0;
        gudangNamafield.setText("");
        gudangAlamatfield.setText("");
        gudangStatusField.setSelectedItem("Aktif");
        //DefaultTableModel model = (DefaultTableModel) tableProdukDetail.getModel();
        //model.setRowCount(0);
    }
    
    protected void setDataUpdateFormIsianGudang(String gudang_id, String gudang_nama, String gudang_alamat, String gudang_status){      
        this.taskFormIsianGudang = "UPDATE";
        this.idUpdateFormIsianGudang = Integer.parseInt(gudang_id);
        // Set Store Data dari Database
        //System.out.print(kategoriNamaProduk);
            
        gudangNamafield.setText(gudang_nama);
        gudangAlamatfield.setText(gudang_alamat);
        gudangStatusField.setSelectedItem(gudang_status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormIsianGudang = new javax.swing.JPanel();
        gudangnamalabel = new javax.swing.JLabel();
        gudangNamafield = new javax.swing.JTextField();
        gudangalamatlabel = new javax.swing.JLabel();
        gudangAlamatfield = new javax.swing.JTextField();
        gudangalamatlabel1 = new javax.swing.JLabel();
        gudangStatusField = new javax.swing.JComboBox<>();
        btnSimpanIsianGudang = new javax.swing.JButton();
        btnKeluarIsiangudang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Isian Gudang");

        panelFormIsianGudang.setBackground(new java.awt.Color(15, 60, 89));

        gudangnamalabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gudangnamalabel.setForeground(new java.awt.Color(255, 255, 255));
        gudangnamalabel.setText("Gudang Nama");

        gudangNamafield.setBackground(new java.awt.Color(51, 51, 51));
        gudangNamafield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gudangNamafield.setForeground(new java.awt.Color(255, 255, 255));
        gudangNamafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gudangNamafieldActionPerformed(evt);
            }
        });

        gudangalamatlabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gudangalamatlabel.setForeground(new java.awt.Color(255, 255, 255));
        gudangalamatlabel.setText("Gudang Alamat");

        gudangAlamatfield.setBackground(new java.awt.Color(51, 51, 51));
        gudangAlamatfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gudangAlamatfield.setForeground(new java.awt.Color(255, 255, 255));

        gudangalamatlabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gudangalamatlabel1.setForeground(new java.awt.Color(255, 255, 255));
        gudangalamatlabel1.setText("Gudang Status");

        gudangStatusField.setBackground(new java.awt.Color(51, 51, 51));
        gudangStatusField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gudangStatusField.setForeground(new java.awt.Color(255, 255, 255));
        gudangStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        gudangStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gudangStatusFieldActionPerformed(evt);
            }
        });

        btnSimpanIsianGudang.setBackground(new java.awt.Color(0, 102, 51));
        btnSimpanIsianGudang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpanIsianGudang.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanIsianGudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/46_save.png"))); // NOI18N
        btnSimpanIsianGudang.setText("Simpan");
        btnSimpanIsianGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanIsianGudangActionPerformed(evt);
            }
        });
        btnSimpanIsianGudang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanIsianGudangKeyPressed(evt);
            }
        });

        btnKeluarIsiangudang.setBackground(new java.awt.Color(0, 153, 153));
        btnKeluarIsiangudang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnKeluarIsiangudang.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluarIsiangudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/01.png"))); // NOI18N
        btnKeluarIsiangudang.setText("Keluar");
        btnKeluarIsiangudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarIsiangudangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormIsianGudangLayout = new javax.swing.GroupLayout(panelFormIsianGudang);
        panelFormIsianGudang.setLayout(panelFormIsianGudangLayout);
        panelFormIsianGudangLayout.setHorizontalGroup(
            panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianGudangLayout.createSequentialGroup()
                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormIsianGudangLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelFormIsianGudangLayout.createSequentialGroup()
                                .addComponent(gudangalamatlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gudangStatusField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelFormIsianGudangLayout.createSequentialGroup()
                                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gudangalamatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gudangnamalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gudangAlamatfield)
                                    .addComponent(gudangNamafield, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelFormIsianGudangLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnSimpanIsianGudang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKeluarIsiangudang)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelFormIsianGudangLayout.setVerticalGroup(
            panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianGudangLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gudangnamalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gudangNamafield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gudangalamatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gudangAlamatfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gudangalamatlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gudangStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelFormIsianGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanIsianGudang)
                    .addComponent(btnKeluarIsiangudang))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gudangNamafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gudangNamafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gudangNamafieldActionPerformed

    private void gudangStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gudangStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gudangStatusFieldActionPerformed

    private void btnSimpanIsianGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanIsianGudangActionPerformed
        if(taskFormIsianGudang.equals("UPDATE")){
            updateDataMasterGudang();
        }else{
            insertDataMasterGudang();
        }
    }//GEN-LAST:event_btnSimpanIsianGudangActionPerformed

    private void btnSimpanIsianGudangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanIsianGudangKeyPressed
        // TODO add your handling code here:
        if(taskFormIsianGudang.equals("UPDATE")){
            updateDataMasterGudang();
        }else{
            insertDataMasterGudang();
        }
    }//GEN-LAST:event_btnSimpanIsianGudangKeyPressed

    private void btnKeluarIsiangudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarIsiangudangActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarIsiangudangActionPerformed
    
    private void updateDataMasterGudang() {
        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "CALL updateGudang(?, ?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, idUpdateFormIsianGudang); // Assuming gudangIdField is the field for Gudang ID
            pst.setString(2, gudangNamafield.getText());
            pst.setString(3, gudangAlamatfield.getText());
            pst.setString(4, (String) gudangStatusField.getSelectedItem());


            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Gudang Berhasil Diupdate!");

                // Call the method to refresh the data after updating
                refreshFormIsianGudang();
                parentIsianGudang.tampilDataKategoriList("");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Gudang Gagal Diupdate!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gudang Gagal Diupdate!");
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gudang Gagal Diupdate!");
            e.printStackTrace();
        }
    }


    public void insertDataMasterGudang(){
                // TODO add your handling code here:
        String gudangNamaValue = gudangNamafield.getText();
        String gudangAlamatValue = gudangAlamatfield.getText();
        String gudangStatusValue = (String) gudangStatusField.getSelectedItem();

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql;

            sql = "CALL insertGudang(?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, gudangNamaValue);
            pst.setString(2, gudangAlamatValue);
            pst.setString(3, gudangStatusValue);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Gudang Berhasil Disimpan!");
            parentIsianGudang.tampilDataKategoriList("");
            this.setVisible(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gudang Gagal Disimpan!");
            // Handle the exception
            e.printStackTrace();  // or log the exception
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gudang Gagal Disimpan!");
            // handle exceptions, at least log them
            e.printStackTrace();
        }
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIsianGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIsianGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIsianGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIsianGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIsianGudang().setVisible(true);
            }
        });
    }
    
    public void setParentisianGudang(ViewMasterGudang parentForm ){
        this.parentIsianGudang = parentForm;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluarIsiangudang;
    private javax.swing.JButton btnSimpanIsianGudang;
    private javax.swing.JTextField gudangAlamatfield;
    private javax.swing.JTextField gudangNamafield;
    private javax.swing.JComboBox<String> gudangStatusField;
    private javax.swing.JLabel gudangalamatlabel;
    private javax.swing.JLabel gudangalamatlabel1;
    private javax.swing.JLabel gudangnamalabel;
    private javax.swing.JPanel panelFormIsianGudang;
    // End of variables declaration//GEN-END:variables

    void taskFormIsianGudang(String update) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
