/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formProduk;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author HP
 */
public class FormIsianProdukDetail extends javax.swing.JFrame {

    /**
     * Creates new form FormIsianProdukDetail
     */
    Map<String, Integer> satuanMap = new HashMap<>();
    private FormIsianProduk parentForm;
    private String taskDetailSatuan = "CREATE";
    private String unixIdDetailSatuan = "";
    
    public FormIsianProdukDetail() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/_asset/78.png");
        setIconImage(icon.getImage());
        setFocusableWindowState(true);
        refreshFormIsianDetail();
        this.taskDetailSatuan = "CREATE";
        this.unixIdDetailSatuan = "";
    }
    
    protected void refreshFormIsianDetail(){
        this.taskDetailSatuan="CREATE";
        this.unixIdDetailSatuan = "";
        cboSatuanField.setSelectedItem(1);
        satuanHargaField.setText("");
        satuanNilaiField.setText("");
        storeSatuanProduk();
    }
    
    protected void setUpdateFormIsianDetail(String pdetailId, String satuanNama, String satuanHarga, String satuanNilai, String satuanDefault){
        this.taskDetailSatuan="UPDATE";
        this.unixIdDetailSatuan = pdetailId;
        storeSatuanProduk();
        cboSatuanField.setSelectedItem(satuanNama);
        satuanHargaField.setText(satuanHarga);
        satuanNilaiField.setText(satuanNilai);
        satuanDefaultField.setSelectedItem(satuanDefault);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboSatuanField = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        satuanHargaField = new javax.swing.JTextField();
        satuanNilaiField = new javax.swing.JTextField();
        satuanDefaultField = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        satuanDefaultLabel = new javax.swing.JLabel();
        btnSimpanProdukDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusableWindowState(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        cboSatuanField.setBackground(new java.awt.Color(51, 51, 51));
        cboSatuanField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboSatuanField.setForeground(new java.awt.Color(255, 255, 255));
        cboSatuanField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Satuan");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga");

        satuanHargaField.setBackground(new java.awt.Color(51, 51, 51));
        satuanHargaField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satuanHargaField.setForeground(new java.awt.Color(255, 255, 255));
        satuanHargaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                satuanHargaFieldFocusGained(evt);
            }
        });

        satuanNilaiField.setBackground(new java.awt.Color(51, 51, 51));
        satuanNilaiField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satuanNilaiField.setForeground(new java.awt.Color(255, 255, 255));

        satuanDefaultField.setBackground(new java.awt.Color(51, 51, 51));
        satuanDefaultField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        satuanDefaultField.setForeground(new java.awt.Color(255, 255, 255));
        satuanDefaultField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ya", "Tidak" }));
        satuanDefaultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanDefaultFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nilai");

        satuanDefaultLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        satuanDefaultLabel.setForeground(new java.awt.Color(255, 255, 255));
        satuanDefaultLabel.setText("Default");

        btnSimpanProdukDetail.setBackground(new java.awt.Color(0, 0, 153));
        btnSimpanProdukDetail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpanProdukDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanProdukDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/46_save.png"))); // NOI18N
        btnSimpanProdukDetail.setText("Simpan");
        btnSimpanProdukDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanProdukDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(satuanDefaultLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(cboSatuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(satuanDefaultField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(satuanHargaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(satuanNilaiField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpanProdukDetail)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboSatuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(satuanHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satuanNilaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satuanDefaultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuanDefaultLabel))
                .addGap(18, 18, 18)
                .addComponent(btnSimpanProdukDetail)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satuanHargaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_satuanHargaFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanHargaFieldFocusGained

    private void satuanDefaultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanDefaultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanDefaultFieldActionPerformed

    private void btnSimpanProdukDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanProdukDetailActionPerformed
        if(taskDetailSatuan.equalsIgnoreCase("UPDATE")){
            updateRowTableSatuan();
        }else{
            insertRowTableSatuan();
        }
    }//GEN-LAST:event_btnSimpanProdukDetailActionPerformed
    
    public void insertRowTableSatuan(){
        // TODO add your handling code here:
        String pdetailSatuanNamaValue = (String) cboSatuanField.getSelectedItem();
        String pdetailHargaValue = satuanHargaField.getText();
        String pdetailNilaiValue = satuanNilaiField.getText();
        String pdetailDefaultValue = (String) satuanDefaultField.getSelectedItem();

        try {
            // Check if the selected value exists in the satuanMap
            if (satuanMap.containsKey(pdetailSatuanNamaValue)) {
                // Get the kategoriId from the map based on the selected kategoriNama
                int pdetailSatuanId = satuanMap.get(pdetailSatuanNamaValue);
                
                // Call the method in the parent FormIsianProduk to add the row
                parentForm.addRowTableSatuan(pdetailSatuanId, pdetailSatuanNamaValue, pdetailHargaValue, pdetailNilaiValue, pdetailDefaultValue);

                // Close the current FormIsianProdukDetail
                this.dispose();

                JOptionPane.showMessageDialog(this, "Produk Detail Berhasil Disimpan!");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Satuan not found in the map: " + pdetailSatuanNamaValue);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Produk Gagal Disimpan!");
            // handle exceptions, at least log them
            e.printStackTrace();
        }
        // Handle the exception
        // or log the exception
    }
    
    public void updateRowTableSatuan(){
        // TODO add your handling code here:
        String pdetailSatuanNamaValue = (String) cboSatuanField.getSelectedItem();
        String pdetailHargaValue = satuanHargaField.getText();
        String pdetailNilaiValue = satuanNilaiField.getText();
        String pdetailDefaultValue = (String) satuanDefaultField.getSelectedItem();

        try {
            // Check if the selected value exists in the satuanMap
            if (satuanMap.containsKey(pdetailSatuanNamaValue)) {
                // Get the kategoriId from the map based on the selected kategoriNama
                int pdetailSatuanId = satuanMap.get(pdetailSatuanNamaValue);
                
                // Call the method in the parent FormIsianProduk to add the row
                parentForm.updateRowTableSatuan(this.unixIdDetailSatuan, pdetailSatuanId, pdetailSatuanNamaValue, pdetailHargaValue, pdetailNilaiValue, pdetailDefaultValue);

                // Close the current FormIsianProdukDetail
                this.dispose();

                JOptionPane.showMessageDialog(this, "Produk Detail Berhasil Disimpan!");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Satuan not found in the map: " + pdetailSatuanNamaValue);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Produk Gagal Disimpan!");
            // handle exceptions, at least log them
            e.printStackTrace();
        }
        // Handle the exception
        // or log the exception
    }
        
    public void storeSatuanProduk() {
        // Assuming you have a database connection 'conn'

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "SELECT satuan_id, satuan_kode FROM produk_satuan WHERE satuan_status='Aktif'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            List<String> items = new ArrayList<>();  // Initialize the list

            while (rs.next()) {
                int satuanId = rs.getInt("satuan_id");
                String satuanNama = rs.getString("satuan_kode");

                // Add the display value to the ComboBox
                items.add(satuanNama);

                // Add the association to the Map
                satuanMap.put(satuanNama, satuanId);
            }

            // Populate the ComboBox with the items
            cboSatuanField.setModel(new DefaultComboBoxModel<>(items.toArray(new String[0])));

            // Add a listener to get the selected value and use the Map to get the corresponding ID
            cboSatuanField.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String selectedSatuanNama = (String) cboSatuanField.getSelectedItem();
                    int selectedSatuanId = satuanMap.get(selectedSatuanNama);
                    // Use the selectedKategoriId as needed
                }
            });

            pst.close();

        } catch (SQLException e) {
            e.printStackTrace();
            // Handle exception appropriately
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIsianProdukDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIsianProdukDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIsianProdukDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIsianProdukDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIsianProdukDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanProdukDetail;
    private javax.swing.JComboBox<String> cboSatuanField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> satuanDefaultField;
    private javax.swing.JLabel satuanDefaultLabel;
    private javax.swing.JTextField satuanHargaField;
    private javax.swing.JTextField satuanNilaiField;
    // End of variables declaration//GEN-END:variables

    public void setParentForm(FormIsianProduk parentForm) {
        this.parentForm = parentForm;
    }
}
