/*pemasokStatusField
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formPemasok;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class FormIsianPemasok extends javax.swing.JFrame {

    /**
     * Creates new form FormIsianPemasok
     */
    
    Map<String, Integer> kategoriMap = new HashMap<>();
    private String taskFormIsianPemasok = "CREATE";
    private int idUpdateFormIsianPemasok = 0;
    private ViewMasterPemasok parentIsianPemasok;
    
    public FormIsianPemasok() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/_asset/78.png");
        setIconImage(icon.getImage());
        refreshFormIsianPemasok();
        pemasokNamaField.setText("");
        pemasokAlamatField.setText("");
        pemasokTlpField.setText("");
        pemasokStatusField.setSelectedItem("Aktif");
    }
    
    protected void refreshFormIsianPemasok(){
        this.taskFormIsianPemasok = "CREATE";
        this.idUpdateFormIsianPemasok = 0;
        pemasokNamaField.setText("");
        pemasokAlamatField.setText("");
        pemasokTlpField.setText("");
        pemasokStatusField.setSelectedItem("Aktif");
    }
    
    protected void setDataUpdateFormIsianPemasok(String pemasok_id, String pemasok_nama, String pemasok_alamat, String pemasok_tlp, String pemasok_status){      
        this.taskFormIsianPemasok = "UPDATE";
        this.idUpdateFormIsianPemasok = Integer.parseInt(pemasok_id);
        // Set Store Data dari Database
        //System.out.print(kategoriNamaProduk);
            
        pemasokNamaField.setText(pemasok_nama);
        pemasokAlamatField.setText(pemasok_alamat);
        pemasokTlpField.setText(pemasok_tlp);
        pemasokStatusField.setSelectedItem(pemasok_status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormIsianPemasok = new javax.swing.JPanel();
        pemasokNamaLabel = new javax.swing.JLabel();
        pemasokNamaField = new javax.swing.JTextField();
        pemasokAlamatLabel = new javax.swing.JLabel();
        pemasokAlamatField = new javax.swing.JTextField();
        pemasokTlpLabel = new javax.swing.JLabel();
        pemasokTlpField = new javax.swing.JTextField();
        pemasokStatusLabel = new javax.swing.JLabel();
        pemasokStatusField = new javax.swing.JComboBox<>();
        btnSimpanIsianPemasok = new javax.swing.JButton();
        btnKeluarIsianPemasok = new javax.swing.JButton();

        panelFormIsianPemasok.setBackground(new java.awt.Color(15, 60, 89));

        pemasokNamaLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pemasokNamaLabel.setForeground(new java.awt.Color(255, 255, 255));
        pemasokNamaLabel.setText("Pemasok Nama");

        pemasokNamaField.setBackground(new java.awt.Color(51, 51, 51));
        pemasokNamaField.setForeground(new java.awt.Color(255, 255, 255));
        pemasokNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokNamaFieldActionPerformed(evt);
            }
        });

        pemasokAlamatLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pemasokAlamatLabel.setForeground(new java.awt.Color(255, 255, 255));
        pemasokAlamatLabel.setText("Pemasok Alamat");

        pemasokAlamatField.setBackground(new java.awt.Color(51, 51, 51));
        pemasokAlamatField.setForeground(new java.awt.Color(255, 255, 255));
        pemasokAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokAlamatFieldActionPerformed(evt);
            }
        });

        pemasokTlpLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pemasokTlpLabel.setForeground(new java.awt.Color(255, 255, 255));
        pemasokTlpLabel.setText("Pemasok Tlp");

        pemasokTlpField.setBackground(new java.awt.Color(51, 51, 51));
        pemasokTlpField.setForeground(new java.awt.Color(255, 255, 255));
        pemasokTlpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokTlpFieldActionPerformed(evt);
            }
        });

        pemasokStatusLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pemasokStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        pemasokStatusLabel.setText("Pemasok Status");

        pemasokStatusField.setBackground(new java.awt.Color(51, 51, 51));
        pemasokStatusField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pemasokStatusField.setForeground(new java.awt.Color(255, 255, 255));
        pemasokStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        pemasokStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokStatusFieldActionPerformed(evt);
            }
        });

        btnSimpanIsianPemasok.setBackground(new java.awt.Color(0, 102, 51));
        btnSimpanIsianPemasok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpanIsianPemasok.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanIsianPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/46_save.png"))); // NOI18N
        btnSimpanIsianPemasok.setText("Simpan");
        btnSimpanIsianPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanIsianPemasokActionPerformed(evt);
            }
        });

        btnKeluarIsianPemasok.setBackground(new java.awt.Color(0, 153, 153));
        btnKeluarIsianPemasok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnKeluarIsianPemasok.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluarIsianPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/01.png"))); // NOI18N
        btnKeluarIsianPemasok.setText("Keluar");
        btnKeluarIsianPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarIsianPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormIsianPemasokLayout = new javax.swing.GroupLayout(panelFormIsianPemasok);
        panelFormIsianPemasok.setLayout(panelFormIsianPemasokLayout);
        panelFormIsianPemasokLayout.setHorizontalGroup(
            panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianPemasokLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnSimpanIsianPemasok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluarIsianPemasok)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFormIsianPemasokLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFormIsianPemasokLayout.createSequentialGroup()
                            .addComponent(pemasokNamaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pemasokNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFormIsianPemasokLayout.createSequentialGroup()
                            .addComponent(pemasokAlamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pemasokAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormIsianPemasokLayout.createSequentialGroup()
                            .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pemasokTlpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pemasokStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pemasokStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pemasokTlpField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(34, 34, 34)))
        );
        panelFormIsianPemasokLayout.setVerticalGroup(
            panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormIsianPemasokLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanIsianPemasok)
                    .addComponent(btnKeluarIsianPemasok))
                .addGap(50, 50, 50))
            .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFormIsianPemasokLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pemasokNamaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pemasokNamaField))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pemasokAlamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pemasokAlamatField))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pemasokTlpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pemasokTlpField))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelFormIsianPemasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pemasokStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pemasokStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(107, 107, 107)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianPemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianPemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pemasokNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemasokNamaFieldActionPerformed

    private void pemasokAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemasokAlamatFieldActionPerformed

    private void pemasokTlpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokTlpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemasokTlpFieldActionPerformed

    private void pemasokStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemasokStatusFieldActionPerformed

    private void btnSimpanIsianPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanIsianPemasokActionPerformed
        // TODO add your handling code here:
        if(taskFormIsianPemasok.equals("UPDATE")){
            updateDataMasterPemasok();
        }else{
            insertDataMasterPemasok();
        }
    }//GEN-LAST:event_btnSimpanIsianPemasokActionPerformed

    private void btnKeluarIsianPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarIsianPemasokActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarIsianPemasokActionPerformed
    
    private void updateDataMasterPemasok() {
        String pemasokNamaValue = pemasokNamaField.getText();
        String pemasokAlamatValue = pemasokAlamatField.getText();
        String pemasokTlpValue = pemasokTlpField.getText();
        String pemasokStatusValue = (String) pemasokStatusField.getSelectedItem();

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql;
            
            sql = "call updatePemasok(?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, pemasokNamaValue);
            pst.setString(2, pemasokAlamatValue);
            pst.setString(3, pemasokTlpValue);
            pst.setString(4, pemasokStatusValue);
            pst.setInt(5, idUpdateFormIsianPemasok);
            
            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Pemasok Berhasil Diupdate!");

                // Call the method to refresh the data after updating
                parentIsianPemasok.tampilDataIsianPemasok("");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Pemasok Gagal Diupdate!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Pemasok Gagal Disimpan!");
            // Handle the exception
            e.printStackTrace();  // or log the exception
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pemasok Gagal Disimpan!");
            // handle exceptions, at least log them
            e.printStackTrace();
        }
    }
    
    private void insertDataMasterPemasok() {
        String pemasokNamaValue = pemasokNamaField.getText();
        String pemasokAlamatValue = pemasokAlamatField.getText();
        String pemasokTlpValue = pemasokTlpField.getText();
        String pemasokStatusValue = (String) pemasokStatusField.getSelectedItem();

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql;
            
            sql = "call insertPemasok(?, ?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, pemasokNamaValue);
            pst.setString(2, pemasokAlamatValue);
            pst.setString(3, pemasokTlpValue);
            pst.setString(4, pemasokStatusValue);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Pemasok Berhasil Disimpan!");
            parentIsianPemasok.tampilDataIsianPemasok("");
            this.setVisible(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Pemasok Gagal Disimpan!");
            // Handle the exception
            e.printStackTrace();  // or log the exception
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pemasok Gagal Disimpan!");
            // handle exceptions, at least log them
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIsianPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIsianPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIsianPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIsianPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIsianPemasok().setVisible(true);
            }
        });
    }
    
    public void setParentisianPemasok(ViewMasterPemasok parentForm ){
        this.parentIsianPemasok = parentForm;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluarIsianPemasok;
    private javax.swing.JButton btnSimpanIsianPemasok;
    private javax.swing.JPanel panelFormIsianPemasok;
    private javax.swing.JTextField pemasokAlamatField;
    private javax.swing.JLabel pemasokAlamatLabel;
    private javax.swing.JTextField pemasokNamaField;
    private javax.swing.JLabel pemasokNamaLabel;
    private javax.swing.JComboBox<String> pemasokStatusField;
    private javax.swing.JLabel pemasokStatusLabel;
    private javax.swing.JTextField pemasokTlpField;
    private javax.swing.JLabel pemasokTlpLabel;
    // End of variables declaration//GEN-END:variables
}
