/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formTransaksiPenjualan;

import database.Koneksi;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class ViewTransaksiPenjualan extends javax.swing.JInternalFrame {
   
    /**
     * Creates new form ViewTransaksiPenjualan
     */
    
    private FormIsianTransaksiPenjualan isianTransaksiPenjualan;
    
    public ViewTransaksiPenjualan() {
        isianTransaksiPenjualan = new FormIsianTransaksiPenjualan();
        initComponents();
        tampilDataPenjualanList("");
    }
    
    // Start fn hide column by name column
    public void hideColumnsByName(JTable table, String... columnNames) {
        for (String columnName : columnNames) {
            int columnIndexToHide = -1;

            for (int i = 0; i < table.getColumnCount(); i++) {
                // Case-insensitive comparison
                if (table.getColumnName(i).equalsIgnoreCase(columnName)) {
                    columnIndexToHide = i;
                    break;
                }
            }

            if (columnIndexToHide != -1) {
                // Set the width of the column to 0 to hide it
                table.getColumnModel().getColumn(columnIndexToHide).setMinWidth(0);
                table.getColumnModel().getColumn(columnIndexToHide).setMaxWidth(0);
                table.getColumnModel().getColumn(columnIndexToHide).setWidth(0);
            } else {
                System.out.println("Column not found: " + columnName);
            }
        }
    }
    
    // start fn tampil data penjualan list
    public void tampilDataPenjualanList(String cariData){
        DefaultTableModel listTableMasterProduk = new DefaultTableModel();
        listTableMasterProduk.addColumn("Penjualan Id");
        listTableMasterProduk.addColumn("Pelanggan Id");
        listTableMasterProduk.addColumn("Tanggal");
        listTableMasterProduk.addColumn("Nomor Faktur");
        listTableMasterProduk.addColumn("Pelanggan");
        listTableMasterProduk.addColumn("Cara Bayar");
        listTableMasterProduk.addColumn("Total Rp");
        listTableMasterProduk.addColumn("Bayar Rp");
        listTableMasterProduk.addColumn("Kembalian");
        listTableMasterProduk.addColumn("Keterangan");
        

        try {
              java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
              String sql = "{CALL SearchTransaksiPenjualan(?)}";
              java.sql.CallableStatement cst = conn.prepareCall(sql);
              cst.setString(1, cariData);

              ResultSet rs = cst.executeQuery();
             
              while (rs.next()) {
                listTableMasterProduk.addRow(new Object[]{
                    rs.getString("penjualan_id"),
                    rs.getString("pelanggan_id"),
                    rs.getString("penjualan_tanggal"),
                    rs.getString("penjualan_nomor_faktur"),
                    rs.getString("pelanggan_nama"),
                    rs.getString("penjualan_cara_bayar"),
                    rs.getString("penjualan_total_rp"),
                    rs.getString("penjualan_bayar_rp"),
                    rs.getString("penjualan_kembalian_rp"),
                    rs.getString("penjualan_keterangan")
                });
            }
            
            tableGridPenjualan.setModel(new DefaultTableModel());

            tableGridPenjualan.setModel(listTableMasterProduk);
            hideColumnsByName(tableGridPenjualan, "Penjualan Id", "Pelanggan Id");
        } catch (SQLException e) {
            // Handle the exception
            e.printStackTrace();  // or log the exception
        } catch (Exception e) {
            // handle exceptions, at least log them
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambahPenjualan = new javax.swing.JButton();
        btnUbahPenjualan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGridPenjualan = new javax.swing.JTable();
        cariPenjualanField = new javax.swing.JTextField();
        btnRefreshPenjualan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Transaksi Penjualan");

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        btnTambahPenjualan.setBackground(new java.awt.Color(0, 0, 153));
        btnTambahPenjualan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambahPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/03.png"))); // NOI18N
        btnTambahPenjualan.setText("Tambah Transaksi Penjualan");
        btnTambahPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPenjualanActionPerformed(evt);
            }
        });

        btnUbahPenjualan.setBackground(new java.awt.Color(0, 0, 153));
        btnUbahPenjualan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUbahPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/19_edit.png"))); // NOI18N
        btnUbahPenjualan.setText("Ubah Transaksi Penjualan");
        btnUbahPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPenjualanActionPerformed(evt);
            }
        });

        tableGridPenjualan.setBackground(new java.awt.Color(51, 51, 51));
        tableGridPenjualan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableGridPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        tableGridPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Penjualan Id", "Pelanggan Id", "Tanggal", "Nomor Faktur", "Pelanggan", "Cara Bayar", "Total Rp", "Bayar Rp", "Kembalian Rp", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tableGridPenjualan);

        cariPenjualanField.setBackground(new java.awt.Color(51, 51, 51));
        cariPenjualanField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cariPenjualanField.setForeground(new java.awt.Color(255, 255, 255));
        cariPenjualanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPenjualanFieldActionPerformed(evt);
            }
        });
        cariPenjualanField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariPenjualanFieldKeyPressed(evt);
            }
        });

        btnRefreshPenjualan.setBackground(new java.awt.Color(0, 0, 153));
        btnRefreshPenjualan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefreshPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/22.png"))); // NOI18N
        btnRefreshPenjualan.setText("Refresh");
        btnRefreshPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPenjualanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pencarian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariPenjualanField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariPenjualanField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPenjualanActionPerformed
        // TODO add your handling code here:
        if( ! ( isianTransaksiPenjualan.isVisible() ) ) { // Memeriksa apakah menuProduk sedang tidak tampil
            Component parentComponent = null; // Replace with the actual component reference
            isianTransaksiPenjualan.refreshIsianPenjualan();
            isianTransaksiPenjualan.setLocationRelativeTo(parentComponent);
            isianTransaksiPenjualan.setVisible(true);
            isianTransaksiPenjualan.setParentForm(this);
        }
        else {
            isianTransaksiPenjualan.requestFocusInWindow();
            isianTransaksiPenjualan.setFocusable(true);
            JOptionPane.showMessageDialog(this, "Form Tambah Detail Sudah Terbuka, Silahkan Lengkapi data dahulu.");
        }
    }//GEN-LAST:event_btnTambahPenjualanActionPerformed

    private void btnUbahPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPenjualanActionPerformed
        int selectedRowIndex = tableGridPenjualan.getSelectedRow();

        if (selectedRowIndex == -1) {
            // No row is selected, show a message
            JOptionPane.showMessageDialog(this, "Tidak Ada Data Yang Dipilih, Mohon Cek Kembali.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            setFormUpdatePenjualan();
        }
    }//GEN-LAST:event_btnUbahPenjualanActionPerformed

    private void cariPenjualanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPenjualanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariPenjualanFieldActionPerformed

    private void cariPenjualanFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariPenjualanFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String enteredText = cariPenjualanField.getText();
            tampilDataPenjualanList(enteredText);
        }
    }//GEN-LAST:event_cariPenjualanFieldKeyPressed

    private void btnRefreshPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPenjualanActionPerformed
        tampilDataPenjualanList("");
    }//GEN-LAST:event_btnRefreshPenjualanActionPerformed

    public void setFormUpdatePenjualan(){
        int selectedRowIndex = tableGridPenjualan.getSelectedRow();
        
        // A row is selected, retrieve data and perform the update
        String penjualanId = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 0);
        String tanggalFaktur = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 2);
        String nomorFaktur = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 3);
        String pelangganNama = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 4);
        String caraBayar = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 5);
        String totalRp = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 6);
        String bayarRp = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 7);
        String KembalianRp = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 8);
        String keterangan = (String) tableGridPenjualan.getValueAt(selectedRowIndex, 9);
        
        // System.out.println(idProduk);
        // System.out.println(kategoriIdProduk);

        Component parentComponent = null; // Replace with the actual component reference
        isianTransaksiPenjualan.setLocationRelativeTo(parentComponent);
        isianTransaksiPenjualan.setParentForm(this);
        isianTransaksiPenjualan.setUpdateDetailPenjualan(
            penjualanId, pelangganNama, tanggalFaktur, nomorFaktur, caraBayar, totalRp, bayarRp, KembalianRp, keterangan
        );
        isianTransaksiPenjualan.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshPenjualan;
    private javax.swing.JButton btnTambahPenjualan;
    private javax.swing.JButton btnUbahPenjualan;
    private javax.swing.JTextField cariPenjualanField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGridPenjualan;
    // End of variables declaration//GEN-END:variables
}
