/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formPelanggan;
import formKaryawan.FormIsianKaryawan;
import formProduk.FormIsianProdukDetail;
import java.awt.Component;
import java.sql.*;
import java.text.Format;
import javax.swing.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.sql.CallableStatement;
/**
 *
 * @author okkyh
 */
public class FormIsianPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form FormIsianPelanggan
     */
    Map<String, Integer> kategoriMap = new HashMap<>();
    private String taskFormIsianPelanggan = "CREATE";
    private int idUpdateFormIsianPelanggan = 0;
    private ViewMasterPelanggan parentIsianPelanggan;

    public FormIsianPelanggan() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/_asset/78.png");
        setIconImage(icon.getImage());
        refreshFormIsian();
        pelangganNamaField.setText("");
        pelangganAlamatField.setText("");
        pelangganNotlpField.setText("");
        pelangganJenisField.setText("");
        pelangganStatusField.setSelectedItem("Aktif");
    }

    protected void refreshFormIsian(){
        this.taskFormIsianPelanggan = "CREATE";
        this.idUpdateFormIsianPelanggan = 0;
        pelangganNamaField.setText("");
        pelangganAlamatField.setText("");
        pelangganNotlpField.setText("");
        pelangganJenisField.setText("");
        pelangganStatusField.setSelectedItem("Aktif");
    }

    protected void setDataUpdateFormIsianPelanggan(String pelanggan_id, String pelanggan_nama, String pelanggan_alamat, String pelanggan_tlp, String pelanggan_jenis_kelamin, String pelanggan_status){      
        this.taskFormIsianPelanggan = "UPDATE";
        this.idUpdateFormIsianPelanggan = Integer.parseInt(pelanggan_id);
        // Set Store Data dari Database
        //System.out.print(kategoriNamaProduk);
            
        pelangganNamaField.setText(pelanggan_nama);
        pelangganAlamatField.setText(pelanggan_alamat);
        pelangganNotlpField.setText(pelanggan_tlp);
        pelangganJenisField.setText(pelanggan_jenis_kelamin);
        pelangganStatusField.setSelectedItem(pelanggan_status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormIsianPelanggan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pelangganNamaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pelangganAlamatField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pelangganNotlpField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pelangganJenisField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pelangganStatusField = new javax.swing.JComboBox<>();
        btnSimpanPelanggan = new javax.swing.JButton();
        btnKeluarIsianPelanggan = new javax.swing.JButton();

        setTitle("Pelanggan");

        panelFormIsianPelanggan.setBackground(new java.awt.Color(15, 60, 89));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Lengkap");

        pelangganNamaField.setBackground(new java.awt.Color(51, 51, 51));
        pelangganNamaField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pelangganNamaField.setForeground(new java.awt.Color(255, 255, 255));
        pelangganNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganNamaFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alamat");

        pelangganAlamatField.setBackground(new java.awt.Color(51, 51, 51));
        pelangganAlamatField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pelangganAlamatField.setForeground(new java.awt.Color(255, 255, 255));
        pelangganAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganAlamatFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Tlp");

        pelangganNotlpField.setBackground(new java.awt.Color(51, 51, 51));
        pelangganNotlpField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pelangganNotlpField.setForeground(new java.awt.Color(255, 255, 255));
        pelangganNotlpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganNotlpFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");

        pelangganJenisField.setBackground(new java.awt.Color(51, 51, 51));
        pelangganJenisField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pelangganJenisField.setForeground(new java.awt.Color(255, 255, 255));
        pelangganJenisField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganJenisFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");

        pelangganStatusField.setBackground(new java.awt.Color(51, 51, 51));
        pelangganStatusField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pelangganStatusField.setForeground(new java.awt.Color(255, 255, 255));
        pelangganStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        pelangganStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganStatusFieldActionPerformed(evt);
            }
        });

        btnSimpanPelanggan.setBackground(new java.awt.Color(0, 102, 51));
        btnSimpanPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpanPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/46_save.png"))); // NOI18N
        btnSimpanPelanggan.setText("Simpan");
        btnSimpanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPelangganActionPerformed(evt);
            }
        });

        btnKeluarIsianPelanggan.setBackground(new java.awt.Color(0, 153, 153));
        btnKeluarIsianPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnKeluarIsianPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluarIsianPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/01.png"))); // NOI18N
        btnKeluarIsianPelanggan.setText("Keluar");
        btnKeluarIsianPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarIsianPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormIsianPelangganLayout = new javax.swing.GroupLayout(panelFormIsianPelanggan);
        panelFormIsianPelanggan.setLayout(panelFormIsianPelangganLayout);
        panelFormIsianPelangganLayout.setHorizontalGroup(
            panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianPelangganLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormIsianPelangganLayout.createSequentialGroup()
                        .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pelangganStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pelangganJenisField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(224, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormIsianPelangganLayout.createSequentialGroup()
                        .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormIsianPelangganLayout.createSequentialGroup()
                                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(55, 55, 55)
                                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pelangganAlamatField)
                                    .addGroup(panelFormIsianPelangganLayout.createSequentialGroup()
                                        .addComponent(pelangganNotlpField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 84, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormIsianPelangganLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(pelangganNamaField)))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormIsianPelangganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpanPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluarIsianPelanggan)
                .addGap(134, 134, 134))
        );
        panelFormIsianPelangganLayout.setVerticalGroup(
            panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianPelangganLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pelangganNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pelangganAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pelangganNotlpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pelangganJenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pelangganStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelFormIsianPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPelanggan)
                    .addComponent(btnKeluarIsianPelanggan))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganNamaFieldActionPerformed

    private void pelangganAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganAlamatFieldActionPerformed

    private void pelangganNotlpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganNotlpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganNotlpFieldActionPerformed

    private void pelangganJenisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganJenisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganJenisFieldActionPerformed

    private void pelangganStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganStatusFieldActionPerformed

    private void btnSimpanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPelangganActionPerformed
        if(taskFormIsianPelanggan.equals("UPDATE")){
            updateDataMasterPelanggan();
        }else{
            insertDataMasterPelanggan();
        }
    }//GEN-LAST:event_btnSimpanPelangganActionPerformed

    private void btnKeluarIsianPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarIsianPelangganActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarIsianPelangganActionPerformed

       private void updateDataMasterPelanggan() {
        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "{CALL UpdatePelanggan(?, ?, ?, ?, ?, ?)}";
            try (CallableStatement cst = conn.prepareCall(sql)) {
                cst.setString(1, pelangganNamaField.getText());
                cst.setString(2, pelangganAlamatField.getText());
                cst.setString(3, pelangganNotlpField.getText());
                cst.setString(4, pelangganJenisField.getText());
                cst.setString(5, (String) pelangganStatusField.getSelectedItem());
                cst.setInt(6, idUpdateFormIsianPelanggan);

                int rowsAffected = cst.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Pelanggan Berhasil Diupdate!");

                    // Panggil metode untuk menyegarkan data setelah pembaruan
                    refreshFormIsian();
                    parentIsianPelanggan.tampilDataList("");
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Pelanggan Gagal Diupdate!");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Pelanggan Gagal Diupdate! Error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pelanggan Gagal Diupdate! Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
     

        public void insertDataMasterPelanggan(){
            // TODO add your handling code here:
            String pelangganNamaValue = pelangganNamaField.getText();
            String pelangganAlamatValue = pelangganAlamatField.getText();
            String pelangganNotlpValue = pelangganNotlpField.getText();
            String pelangganJenisValue = pelangganJenisField.getText();
            String pelangganStatusValue = (String) pelangganStatusField.getSelectedItem();

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "{CALL InsertPelanggan(?, ?, ?, ?, ?)}";
            try (CallableStatement cst = conn.prepareCall(sql)) {
                cst.setString(1, pelangganNamaValue);
                cst.setString(2, pelangganAlamatValue);
                cst.setString(3, pelangganNotlpValue);
                cst.setString(4, pelangganJenisValue);
                cst.setString(5, pelangganStatusValue);

                cst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Pelanggan Berhasil Disimpan!");
                parentIsianPelanggan.tampilDataList("");
                this.setVisible(false);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Pelanggan Gagal Disimpan!");
            // Handle the exception
            e.printStackTrace();  // or log the exception
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pelanggan Gagal Disimpan!");
            // handle exceptions, at least log them
            e.printStackTrace();
        }
    }
        
    public void setParentisianPelanggan(ViewMasterPelanggan parentForm ){
        this.parentIsianPelanggan = parentForm;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIsianPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIsianPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIsianPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIsianPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIsianPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluarIsianPelanggan;
    private javax.swing.JButton btnSimpanPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelFormIsianPelanggan;
    private javax.swing.JTextField pelangganAlamatField;
    private javax.swing.JTextField pelangganJenisField;
    private javax.swing.JTextField pelangganNamaField;
    private javax.swing.JTextField pelangganNotlpField;
    private javax.swing.JComboBox<String> pelangganStatusField;
    // End of variables declaration//GEN-END:variables
}
