/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formSatuan;

import formGudang.ViewMasterGudang;
import java.awt.Component;
import javax.swing.*;
import javax.swing.table.*;
import database.Koneksi;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.CallableStatement;

/**
 *
 * @author okkyh
 */

public class ViewMasterSatuan extends javax.swing.JInternalFrame {

    JasperReport JasRep;
    JasperPrint JasPri;
    Map param = new HashMap();
    JasperDesign JasDes;

    /**
     * Creates new form ViewMasterSatuan
     */
    private FormIsianSatuan isianSatuan;
    private String taskFormIsianSatuan = "CREATE";

    public ViewMasterSatuan() {
        isianSatuan = new FormIsianSatuan();
        initComponents();
        tampilDataList("");
    }
    
    public void tampilDataList(String cariData) {
        DefaultTableModel listTableSatuan = new DefaultTableModel();
        listTableSatuan.addColumn("No");
        listTableSatuan.addColumn("Kode");
        listTableSatuan.addColumn("Nama Satuan");
        listTableSatuan.addColumn("Status");

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "{CALL SearchProdukSatuan(?)}";
            try (CallableStatement cst = conn.prepareCall(sql)) {
                cst.setString(1, cariData);

                ResultSet rs = cst.executeQuery();
                while (rs.next()) {
                    listTableSatuan.addRow(new Object[]{
                        rs.getString("satuan_id"),
                        rs.getString("satuan_kode"),
                        rs.getString("satuan_nama"),
                        rs.getString("satuan_status"),
                    });
                }
                satuanGridTable.setModel(new DefaultTableModel());
                satuanGridTable.setModel(listTableSatuan);
 
            }
        } catch (SQLException e) {
            e.printStackTrace();  // or log the exception
        } catch (Exception e) {
            e.printStackTrace();
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSatuan = new javax.swing.JPanel();
        btnTambahSatuan = new javax.swing.JButton();
        btnUbahSatuan = new javax.swing.JButton();
        pencarianLabel = new javax.swing.JLabel();
        cariSatuanField = new javax.swing.JTextField();
        btnRefreshSatuan1 = new javax.swing.JButton();
        btnCetakSatuan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        satuanGridTable = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Satuan");

        panelSatuan.setBackground(new java.awt.Color(0, 102, 102));

        btnTambahSatuan.setBackground(new java.awt.Color(0, 0, 102));
        btnTambahSatuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambahSatuan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/03.png"))); // NOI18N
        btnTambahSatuan.setText("Tambah Satuan");
        btnTambahSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSatuanActionPerformed(evt);
            }
        });

        btnUbahSatuan.setBackground(new java.awt.Color(0, 0, 102));
        btnUbahSatuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUbahSatuan.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/19_edit.png"))); // NOI18N
        btnUbahSatuan.setText("Ubah Satuan");
        btnUbahSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahSatuanActionPerformed(evt);
            }
        });

        pencarianLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pencarianLabel.setForeground(new java.awt.Color(255, 255, 255));
        pencarianLabel.setText("Pencarian");

        cariSatuanField.setBackground(new java.awt.Color(51, 51, 51));
        cariSatuanField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cariSatuanField.setForeground(new java.awt.Color(255, 255, 255));
        cariSatuanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariSatuanFieldActionPerformed(evt);
            }
        });
        cariSatuanField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariSatuanFieldKeyPressed(evt);
            }
        });

        btnRefreshSatuan1.setBackground(new java.awt.Color(0, 0, 102));
        btnRefreshSatuan1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefreshSatuan1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshSatuan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/22.png"))); // NOI18N
        btnRefreshSatuan1.setText("Refresh");
        btnRefreshSatuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshSatuan1ActionPerformed(evt);
            }
        });

        btnCetakSatuan.setBackground(new java.awt.Color(0, 0, 102));
        btnCetakSatuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCetakSatuan.setForeground(new java.awt.Color(255, 255, 255));
        btnCetakSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/11_print.png"))); // NOI18N
        btnCetakSatuan.setText("Cetak");
        btnCetakSatuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetakSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakSatuanActionPerformed(evt);
            }
        });

        satuanGridTable.setBackground(new java.awt.Color(51, 51, 51));
        satuanGridTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satuanGridTable.setForeground(new java.awt.Color(255, 255, 255));
        satuanGridTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        satuanGridTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                satuanGridTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                satuanGridTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(satuanGridTable);

        javax.swing.GroupLayout panelSatuanLayout = new javax.swing.GroupLayout(panelSatuan);
        panelSatuan.setLayout(panelSatuanLayout);
        panelSatuanLayout.setHorizontalGroup(
            panelSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSatuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelSatuanLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnTambahSatuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbahSatuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pencarianLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cariSatuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshSatuan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakSatuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSatuanLayout.setVerticalGroup(
            panelSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSatuanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbahSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariSatuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshSatuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSatuanActionPerformed
        if( ! ( isianSatuan.isVisible() ) ) { // Memeriksa apakah menuProduk sedang tidak tampil
            Component parentComponent = null; // Replace with the actual component reference
            isianSatuan.setLocationRelativeTo(parentComponent);
            isianSatuan.refreshFormIsian();
            isianSatuan.setParentisianSatuan(this);
            isianSatuan.setVisible(true);
        }
        else {
            isianSatuan.requestFocusInWindow();
            isianSatuan.setFocusable(true);
            JOptionPane.showMessageDialog(this, "Form Tambah Satuan Sudah Terbuka, Silahkan Lengkapi data dahulu.");
        }
    }//GEN-LAST:event_btnTambahSatuanActionPerformed

    private void btnUbahSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahSatuanActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = satuanGridTable.getSelectedRow();

        if (selectedRowIndex == -1) {
            // No row is selected, show a message
            JOptionPane.showMessageDialog(this, "Tidak Ada Data Yang Dipilih, Mohon Cek Kembali.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            setFormUpdateMasterSatuan();
        }
    }//GEN-LAST:event_btnUbahSatuanActionPerformed

    private void cariSatuanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariSatuanFieldActionPerformed

    }//GEN-LAST:event_cariSatuanFieldActionPerformed

    private void cariSatuanFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariSatuanFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // This block will be executed when the Enter key is pressed
            String enteredText = cariSatuanField.getText();
            // Perform your desired action with the entered text
            // For example, you might want to process the entered SKU
            tampilDataList(enteredText);
        }
    }//GEN-LAST:event_cariSatuanFieldKeyPressed

    private void btnRefreshSatuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshSatuan1ActionPerformed
        cariSatuanField.setText("");
        tampilDataList("");
    }//GEN-LAST:event_btnRefreshSatuan1ActionPerformed

    private void btnCetakSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakSatuanActionPerformed
        try {
            Connection konn = new Koneksi().koneksiDB();
            File file = new File("src/_cetak/laporanSatuan.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.put("satuan_id",btnCetakSatuan.getText());
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param, konn);
            //JasperViewer.viewReport(JasPri, false);
            JasperViewer jasperViewer = new JasperViewer(JasPri, false);
            jasperViewer.setExtendedState(jasperViewer.getExtendedState()|javax.swing.JFrame.MAXIMIZED_BOTH);
            jasperViewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal membuka Laporan", "Cetak laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakSatuanActionPerformed

    private void satuanGridTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satuanGridTableMouseClicked

    }//GEN-LAST:event_satuanGridTableMouseClicked

    private void satuanGridTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satuanGridTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanGridTableMousePressed

    public void setFormUpdateMasterSatuan(){
        int selectedRowIndex = satuanGridTable.getSelectedRow();
         
        // A row is selected, retrieve data and perform the update
        String satuan_id = (String) satuanGridTable.getValueAt(selectedRowIndex, 0);
        String satuan_kode = (String) satuanGridTable.getValueAt(selectedRowIndex, 1);
        String satuan_nama = (String) satuanGridTable.getValueAt(selectedRowIndex, 2);
        String satuan_status = (String) satuanGridTable.getValueAt(selectedRowIndex, 3);
        
        Component parentComponent = null; // Replace with the actual component reference
        isianSatuan.setLocationRelativeTo(parentComponent);
        isianSatuan.setDataUpdateFormIsianSatuan(satuan_id,satuan_kode, satuan_nama, satuan_status);
        isianSatuan.setParentisianSatuan(this);
        isianSatuan.setVisible(true);
    }
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMasterGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMasterGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMasterGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMasterGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMasterSatuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakSatuan;
    private javax.swing.JButton btnRefreshSatuan1;
    private javax.swing.JButton btnTambahSatuan;
    private javax.swing.JButton btnUbahSatuan;
    private javax.swing.JTextField cariSatuanField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelSatuan;
    private javax.swing.JLabel pencarianLabel;
    private javax.swing.JTable satuanGridTable;
    // End of variables declaration//GEN-END:variables

}
