/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formKaryawan;
import formProduk.FormIsianProdukDetail;
import java.awt.Component;
import java.sql.*;
import java.text.Format;
import javax.swing.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.sql.CallableStatement;
/**
 *
 * @author okkyh
 */
public class FormIsianKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form FormIsianKaryawan
     */
    Map<String, Integer> kategoriMap = new HashMap<>();
    private String taskFormIsianKaryawan = "CREATE";
    private int idUpdateFormIsianKaryawan = 0;
    private ViewMasterKaryawan parentIsianKaryawan;

public FormIsianKaryawan() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/_asset/78.png");
        setIconImage(icon.getImage());
        refreshFormIsian();
        karyawanNamaField.setText("");
        karyawanAlamatField.setText("");
        karyawanNotlpField.setText("");
        karyawanJenisField.setText("");
        karyawanStatusField.setSelectedItem("Aktif");
    }

protected void refreshFormIsian(){
        this.taskFormIsianKaryawan = "CREATE";
        this.idUpdateFormIsianKaryawan = 0;
        karyawanNamaField.setText("");
        karyawanAlamatField.setText("");
        karyawanNotlpField.setText("");
        karyawanJenisField.setText("");
        karyawanStatusField.setSelectedItem("Aktif");
    }
protected void setDataUpdateFormIsianKaryawan(String karyawan_id, String karyawan_nama, String karyawan_alamat, String karyawan_tlp, String karyawan_jenis_kelamin, String karyawan_status){      
        this.taskFormIsianKaryawan = "UPDATE";
        this.idUpdateFormIsianKaryawan = Integer.parseInt(karyawan_id);
        // Set Store Data dari Database
        //System.out.print(kategoriNamaProduk);
            
        karyawanNamaField.setText(karyawan_nama);
        karyawanAlamatField.setText(karyawan_alamat);
        karyawanNotlpField.setText(karyawan_tlp);
        karyawanJenisField.setText(karyawan_jenis_kelamin);
        karyawanStatusField.setSelectedItem(karyawan_status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormIsianKaryawan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        karyawanNamaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        karyawanAlamatField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        karyawanNotlpField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        karyawanJenisField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        karyawanStatusField = new javax.swing.JComboBox<>();
        btnSimpanKaryawanFormIsian = new javax.swing.JButton();
        btnKeluarIsianPelanggan = new javax.swing.JButton();

        setTitle("Karyawan");

        panelFormIsianKaryawan.setBackground(new java.awt.Color(15, 60, 89));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Lengkap");

        karyawanNamaField.setBackground(new java.awt.Color(51, 51, 51));
        karyawanNamaField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        karyawanNamaField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanNamaFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alamat");

        karyawanAlamatField.setBackground(new java.awt.Color(51, 51, 51));
        karyawanAlamatField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        karyawanAlamatField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanAlamatFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Tlp");

        karyawanNotlpField.setBackground(new java.awt.Color(51, 51, 51));
        karyawanNotlpField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        karyawanNotlpField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanNotlpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanNotlpFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");

        karyawanJenisField.setBackground(new java.awt.Color(51, 51, 51));
        karyawanJenisField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        karyawanJenisField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanJenisField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanJenisFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");

        karyawanStatusField.setBackground(new java.awt.Color(51, 51, 51));
        karyawanStatusField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        karyawanStatusField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        karyawanStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanStatusFieldActionPerformed(evt);
            }
        });

        btnSimpanKaryawanFormIsian.setBackground(new java.awt.Color(0, 102, 51));
        btnSimpanKaryawanFormIsian.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpanKaryawanFormIsian.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanKaryawanFormIsian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/46_save.png"))); // NOI18N
        btnSimpanKaryawanFormIsian.setText("Simpan");
        btnSimpanKaryawanFormIsian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKaryawanFormIsianActionPerformed(evt);
            }
        });

        btnKeluarIsianPelanggan.setBackground(new java.awt.Color(0, 153, 153));
        btnKeluarIsianPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnKeluarIsianPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluarIsianPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/01.png"))); // NOI18N
        btnKeluarIsianPelanggan.setText("Keluar");
        btnKeluarIsianPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarIsianPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormIsianKaryawanLayout = new javax.swing.GroupLayout(panelFormIsianKaryawan);
        panelFormIsianKaryawan.setLayout(panelFormIsianKaryawanLayout);
        panelFormIsianKaryawanLayout.setHorizontalGroup(
            panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianKaryawanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormIsianKaryawanLayout.createSequentialGroup()
                        .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(karyawanJenisField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(karyawanNotlpField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(karyawanStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFormIsianKaryawanLayout.createSequentialGroup()
                                .addComponent(btnSimpanKaryawanFormIsian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKeluarIsianPelanggan)))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormIsianKaryawanLayout.createSequentialGroup()
                        .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(karyawanAlamatField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(karyawanNamaField, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addGap(9, 9, 9))))
        );
        panelFormIsianKaryawanLayout.setVerticalGroup(
            panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormIsianKaryawanLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(karyawanNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(karyawanAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(karyawanNotlpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(karyawanJenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(karyawanStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(panelFormIsianKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanKaryawanFormIsian)
                    .addComponent(btnKeluarIsianPelanggan))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormIsianKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Karyawan Point Of Sales");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void karyawanNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanNamaFieldActionPerformed

    private void karyawanAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanAlamatFieldActionPerformed

    private void karyawanNotlpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanNotlpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanNotlpFieldActionPerformed

    private void karyawanJenisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanJenisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanJenisFieldActionPerformed

    private void karyawanStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanStatusFieldActionPerformed

    private void btnSimpanKaryawanFormIsianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKaryawanFormIsianActionPerformed
        if(taskFormIsianKaryawan.equals("UPDATE")){
            updateDataMasterKaryawan();
        }else{
            insertDataMasterKaryawan();
        }
    }//GEN-LAST:event_btnSimpanKaryawanFormIsianActionPerformed

    private void btnKeluarIsianPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarIsianPelangganActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarIsianPelangganActionPerformed


    private void updateDataMasterKaryawan() {
        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "{CALL UpdateKaryawan(?, ?, ?, ?, ?, ?)}";
            try (CallableStatement cst = conn.prepareCall(sql)) {
                cst.setString(1, karyawanNamaField.getText());
                cst.setString(2, karyawanAlamatField.getText());
                cst.setString(3, karyawanNotlpField.getText());
                cst.setString(4, karyawanJenisField.getText());
                cst.setString(5, (String) karyawanStatusField.getSelectedItem());
                cst.setInt(6, idUpdateFormIsianKaryawan);

                int rowsAffected = cst.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Karyawan Berhasil Diupdate!");

                    // Panggil metode untuk menyegarkan data setelah pembaruan
                    refreshFormIsian();
                    parentIsianKaryawan.tampilDataList("");
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Karyawan Gagal Diupdate!");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Karyawan Gagal Diupdate! Error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Karyawan Gagal Diupdate! Error: " + e.getMessage());
            e.printStackTrace();
        }
    
    }  

        public void insertDataMasterKaryawan(){
            // TODO add your handling code here:
            String karyawanNamaValue = karyawanNamaField.getText();
            String karyawanAlamatValue = karyawanAlamatField.getText();
            String karyawanNotlpValue = karyawanNotlpField.getText();
            String karyawanJenisValue = karyawanJenisField.getText();
            String karyawanStatusValue = (String) karyawanStatusField.getSelectedItem();

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql = "{CALL InsertKaryawan(?, ?, ?, ?, ?)}";
            try (CallableStatement cst = conn.prepareCall(sql)) {
                cst.setString(1, karyawanNamaValue);
                cst.setString(2, karyawanAlamatValue);
                cst.setString(3, karyawanNotlpValue);
                cst.setString(4, karyawanJenisValue);
                cst.setString(5, karyawanStatusValue);

                cst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Karyawan Berhasil Disimpan!");
                parentIsianKaryawan.tampilDataList("");
                this.setVisible(false);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Karyawan Gagal Disimpan! Error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Karyawan Gagal Disimpan! Error: " + e.getMessage());
            e.printStackTrace();
        }
    
    }   
        
    public void setParentisianKaryawan(ViewMasterKaryawan parentForm ){
        this.parentIsianKaryawan = parentForm;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIsianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIsianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIsianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIsianKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIsianKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluarIsianPelanggan;
    private javax.swing.JButton btnSimpanKaryawanFormIsian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField karyawanAlamatField;
    private javax.swing.JTextField karyawanJenisField;
    private javax.swing.JTextField karyawanNamaField;
    private javax.swing.JTextField karyawanNotlpField;
    private javax.swing.JComboBox<String> karyawanStatusField;
    private javax.swing.JPanel panelFormIsianKaryawan;
    // End of variables declaration//GEN-END:variables
}
