/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formKaryawan;

/**
 *
 * @author okkyh
 */

import java.awt.Component;
import javax.swing.*;
import javax.swing.table.*;
import database.Koneksi;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


public class ViewMasterKaryawan extends javax.swing.JInternalFrame {

    JasperReport JasRep;
    JasperPrint JasPri;
    Map param = new HashMap();
    JasperDesign JasDes;
    
    
     private FormIsianKaryawan isianKaryawan;

    public ViewMasterKaryawan() {
        isianKaryawan = new FormIsianKaryawan ();
        initComponents();
        tampilDataList("");
    }

    public final void tampilDataList(String cariData) {
        DefaultTableModel listTableKaryawan = new DefaultTableModel();
        listTableKaryawan.addColumn("No");
        listTableKaryawan.addColumn("Nama Lengkap");
        listTableKaryawan.addColumn("Alamat");
        listTableKaryawan.addColumn("No Tlp");
        listTableKaryawan.addColumn("Jenis Kelamin");
        listTableKaryawan.addColumn("Status");

        try {
            java.sql.Connection conn = (java.sql.Connection) database.Koneksi.koneksiDB();
            String sql;
            
            if (!cariData.isEmpty()) {
                sql = "{CALL SearchKaryawan(?)}";
                
            } else {
                sql = "{CALL SearchKaryawan(?)}";
                       
            }
             java.sql.PreparedStatement pst = conn.prepareCall(sql);
             pst.setString(1, cariData);
             ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                listTableKaryawan.addRow(new Object[]{
                    rs.getString("karyawan_id"),
                    rs.getString("karyawan_nama"),
                    rs.getString("karyawan_alamat"),
                    rs.getString("karyawan_tlp"),
                    rs.getString("karyawan_jenis_kelamin"),
                    rs.getString("karyawan_status"),

                });
            }
            karyawanGridTable.setModel(new DefaultTableModel());
            karyawanGridTable.setModel(listTableKaryawan);

        } catch (SQLException e) {
            // Handle the exception
            // or log the exception
            
        } catch (Exception e) {
            // handle exceptions, at least log them

        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKaryawan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        karyawanPilihanField = new javax.swing.JComboBox<>();
        karyawanCariField = new javax.swing.JTextField();
        btnRefreshKaryawan = new javax.swing.JButton();
        btnTambahKaryawan = new javax.swing.JButton();
        btnUbahKaryawan = new javax.swing.JButton();
        btnCetakKaryawan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        karyawanGridTable = new javax.swing.JTable();

        setClosable(true);
        setTitle("Master Karyawan");
        setAutoscrolls(true);

        panelKaryawan.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setBackground(new java.awt.Color(0, 102, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cari");

        karyawanPilihanField.setBackground(new java.awt.Color(102, 102, 0));
        karyawanPilihanField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        karyawanPilihanField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanPilihanField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Anda", "Nama", "Status", "Jenis Kelamin" }));
        karyawanPilihanField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        karyawanPilihanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanPilihanFieldActionPerformed(evt);
            }
        });

        karyawanCariField.setBackground(new java.awt.Color(51, 51, 51));
        karyawanCariField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        karyawanCariField.setForeground(new java.awt.Color(255, 255, 255));
        karyawanCariField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanCariFieldActionPerformed(evt);
            }
        });
        karyawanCariField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                karyawanCariFieldKeyPressed(evt);
            }
        });

        btnRefreshKaryawan.setBackground(new java.awt.Color(0, 0, 102));
        btnRefreshKaryawan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefreshKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/22.png"))); // NOI18N
        btnRefreshKaryawan.setText("Refresh");
        btnRefreshKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshKaryawanActionPerformed(evt);
            }
        });

        btnTambahKaryawan.setBackground(new java.awt.Color(0, 0, 102));
        btnTambahKaryawan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambahKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/03.png"))); // NOI18N
        btnTambahKaryawan.setText("Tambah Karyawan");
        btnTambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKaryawanActionPerformed(evt);
            }
        });

        btnUbahKaryawan.setBackground(new java.awt.Color(0, 0, 102));
        btnUbahKaryawan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUbahKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/19_edit.png"))); // NOI18N
        btnUbahKaryawan.setText("Ubah Karyawan");
        btnUbahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKaryawanActionPerformed(evt);
            }
        });

        btnCetakKaryawan.setBackground(new java.awt.Color(0, 0, 102));
        btnCetakKaryawan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCetakKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnCetakKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_asset/11_print.png"))); // NOI18N
        btnCetakKaryawan.setText("Cetak");
        btnCetakKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetakKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKaryawanActionPerformed(evt);
            }
        });

        karyawanGridTable.setBackground(new java.awt.Color(51, 51, 51));
        karyawanGridTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        karyawanGridTable.setForeground(new java.awt.Color(255, 255, 255));
        karyawanGridTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        karyawanGridTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanGridTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(karyawanGridTable);

        javax.swing.GroupLayout panelKaryawanLayout = new javax.swing.GroupLayout(panelKaryawan);
        panelKaryawan.setLayout(panelKaryawanLayout);
        panelKaryawanLayout.setHorizontalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(karyawanPilihanField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawanCariField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbahKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(78, 78, 78))
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelKaryawanLayout.setVerticalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(karyawanPilihanField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(karyawanCariField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void karyawanPilihanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanPilihanFieldActionPerformed

    }//GEN-LAST:event_karyawanPilihanFieldActionPerformed

    private void karyawanCariFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanCariFieldActionPerformed

        }

        // Metode untuk mencari dan memfilter berdasarkan nama di dalam tabel
        private void cariDanFilterBerdasarkanNama(String nama) {
            DefaultTableModel model = (DefaultTableModel) karyawanGridTable.getModel();
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            karyawanGridTable.setRowSorter(sorter);

            RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + nama, 0); // Mengabaikan huruf besar/kecil
            sorter.setRowFilter(filter);
        }

        // Metode untuk mencari dan memfilter berdasarkan status di dalam tabel
        private void cariDanFilterBerdasarkanStatus(String status) {
            DefaultTableModel model = (DefaultTableModel) karyawanGridTable.getModel();
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            karyawanGridTable.setRowSorter(sorter);

            RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + status, 4); // Mengabaikan huruf besar/kecil
            sorter.setRowFilter(filter);
    }//GEN-LAST:event_karyawanCariFieldActionPerformed

    private void karyawanCariFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_karyawanCariFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // This block will be executed when the Enter key is pressed
            String enteredText = karyawanCariField.getText();
            // Perform your desired action with the entered text
            // For example, you might want to process the entered SKU
            tampilDataList(enteredText);
        }
    }//GEN-LAST:event_karyawanCariFieldKeyPressed

    private void btnRefreshKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshKaryawanActionPerformed
        // TODO add your handling code here:
        karyawanCariField.setText("");
        tampilDataList("");
    }//GEN-LAST:event_btnRefreshKaryawanActionPerformed

    private void btnTambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKaryawanActionPerformed
        if( ! ( isianKaryawan.isVisible() ) ) { // Memeriksa apakah menuProduk sedang tidak tampil
            Component parentComponent = null; // Replace with the actual component reference
            isianKaryawan.setLocationRelativeTo(parentComponent);
            isianKaryawan.refreshFormIsian();
            isianKaryawan.setParentisianKaryawan(this);
            isianKaryawan.setVisible(true);
        }
        else {
            isianKaryawan.requestFocusInWindow();
            isianKaryawan.setFocusable(true);
            JOptionPane.showMessageDialog(this, "Form Tambah Karyawan Sudah Terbuka, Silahkan Lengkapi data dahulu.");
        }
    }//GEN-LAST:event_btnTambahKaryawanActionPerformed

    private void btnUbahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKaryawanActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = karyawanGridTable.getSelectedRow();

        if (selectedRowIndex == -1) {
            // No row is selected, show a message
            JOptionPane.showMessageDialog(this, "Tidak Ada Data Yang Dipilih, Mohon Cek Kembali.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            setFormUpdateMasterKaryawan();
        }
    }//GEN-LAST:event_btnUbahKaryawanActionPerformed

    private void btnCetakKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKaryawanActionPerformed
        try {
            Connection konn = new Koneksi().koneksiDB();
            File file = new File("src/_cetak/laporanKaryawan.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.put("karyawan_id",btnCetakKaryawan.getText());
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param, konn);
            //JasperViewer.viewReport(JasPri, false);
            JasperViewer jasperViewer = new JasperViewer(JasPri, false);
            jasperViewer.setExtendedState(jasperViewer.getExtendedState()|javax.swing.JFrame.MAXIMIZED_BOTH);
            jasperViewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal membuka Laporan", "Cetak laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakKaryawanActionPerformed

    private void karyawanGridTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanGridTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanGridTableMouseClicked
     
    //Form Update Master Gudang
    public void setFormUpdateMasterKaryawan(){
        int selectedRowIndex = karyawanGridTable.getSelectedRow();
         
        // A row is selected, retrieve data and perform the update
        String karyawan_id = (String) karyawanGridTable.getValueAt(selectedRowIndex, 0);
        String karyawan_nama = (String) karyawanGridTable.getValueAt(selectedRowIndex, 1);
        String karyawan_alamat = (String) karyawanGridTable.getValueAt(selectedRowIndex, 2);
        String karyawan_tlp = (String) karyawanGridTable.getValueAt(selectedRowIndex, 3);
        String karyawan_jenis_kelamin = (String) karyawanGridTable.getValueAt(selectedRowIndex, 4);
        String karyawan_status = (String) karyawanGridTable.getValueAt(selectedRowIndex, 5);
        
        Component parentComponent = null; // Replace with the actual component reference
        
        isianKaryawan.setLocationRelativeTo(parentComponent);
        isianKaryawan.setDataUpdateFormIsianKaryawan(karyawan_id, karyawan_nama, karyawan_alamat, karyawan_tlp, karyawan_jenis_kelamin, karyawan_status);
        isianKaryawan.setParentisianKaryawan(this);
        isianKaryawan.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakKaryawan;
    private javax.swing.JButton btnRefreshKaryawan;
    private javax.swing.JButton btnTambahKaryawan;
    private javax.swing.JButton btnUbahKaryawan;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField karyawanCariField;
    private javax.swing.JTable karyawanGridTable;
    private javax.swing.JComboBox<String> karyawanPilihanField;
    private javax.swing.JPanel panelKaryawan;
    // End of variables declaration//GEN-END:variables


}
